config/routes.rb
Rails.application.routes.draw do
  root to: "courses#index"
  
  get 'pages/home'

  get 'pages/about'

  resources :enrollments

  resources :courses

  resources :departments

  resources :students

  resources :instructors

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails University</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" type="text/css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css" type="text/css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//code.jquery.com/jquery-2.1.3.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
      <div class="container-fluid">
      <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
        <%= link_to "RailsU", root_url, :class => "navbar-brand" %>
      </div>

    <!-- nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_url %></li>
        <li><%= link_to "Students", students_url %></li>
        <li><%= link_to "Courses", courses_url %></li>
        <li><%= link_to "Instructors", instructors_url %></li>
        <li><%= link_to "Departments", departments_url %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <li><a href="#" data-toggle="modal" data-target="#myModal">Sign in</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h2 class="modal-title" id="myModalLabel">Sign in</h2>
        </div>
        <div class="modal-body">
          <form class="form-signin" role="form">
            <h3 class="form-signin-heading">Sign in with your email address</h3>
            <div class="form-group">
              <input type="email" class="form-control" placeholder="Email address" required autofocus>
            </div>
            <div class="form-group">
              <input type="password" class="form-control" placeholder="Password" required>
            </div>
            <div class="checkbox">
              <label>
                <input type="checkbox" value="remember-me"> Remember me
              </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
          </form>
        </div>

        <div class="row">
          <div class="col-xs-3">
            <a href="#" class="btn btn-facebook btn-large btn-caps btn-block">Facebook <span class="icon-facebook"></span></a>
          </div>
          <div class="col-xs-3">
            <a href="" class="btn btn-twitter btn-large btn-caps btn-block">Twitter <span class="icon-twitter"></span></a>
          </div>
          <div class="col-xs-3">
            <a href="" class="btn btn-lg btn-caps btn-block"> <span class="icon-dribbble"></span></a>
          </div>
        </div>

        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>

  <div class="container"> 
    <%= yield %>
  </div>

</body>
</html>